// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/inspector.dart';
import 'api/texture.dart';
import 'api/weapon.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInspectorInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 126338535;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'yp_formats',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiInspectorCloseModel({required BigInt sessionId});

  Future<MiscTexResult> crateApiTextureCreateItemThumbnail({
    required String sourceImagePath,
    required String outputDir,
    required String textureName,
    required int width,
    required int height,
  });

  Future<void> crateApiInspectorInitApp();

  Future<ModelSession> crateApiInspectorOpenModel({
    String? datPath,
    String? dttPath,
    required String candidateId,
  });

  Future<ArchiveProbe> crateApiInspectorProbeArchivePair({
    String? datPath,
    String? dttPath,
  });

  Future<TexturePreview> crateApiTextureReadMisctexPreview({
    required String dttPath,
  });

  Future<WeaponRenameResult> crateApiWeaponRenameWeapon({
    required String datPath,
    required String dttPath,
    required String toStem,
    required String outDir,
  });

  Future<RenderFrame> crateApiInspectorRenderModel({
    required BigInt sessionId,
    required int width,
    required int height,
    required double yaw,
    required double pitch,
    required double distance,
    required double panX,
    required double panY,
  });

  Future<void> crateApiInspectorSetMeshVisibility({
    required BigInt sessionId,
    required int meshId,
    required bool visible,
  });

  Future<void> crateApiInspectorSetModelLod({
    required BigInt sessionId,
    required int lodIndex,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiInspectorCloseModel({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInspectorCloseModelConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorCloseModelConstMeta =>
      const TaskConstMeta(debugName: "close_model", argNames: ["sessionId"]);

  @override
  Future<MiscTexResult> crateApiTextureCreateItemThumbnail({
    required String sourceImagePath,
    required String outputDir,
    required String textureName,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceImagePath, serializer);
          sse_encode_String(outputDir, serializer);
          sse_encode_String(textureName, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_misc_tex_result,
          decodeErrorData: sse_decode_misc_tex_error,
        ),
        constMeta: kCrateApiTextureCreateItemThumbnailConstMeta,
        argValues: [sourceImagePath, outputDir, textureName, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTextureCreateItemThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "create_item_thumbnail",
        argNames: [
          "sourceImagePath",
          "outputDir",
          "textureName",
          "width",
          "height",
        ],
      );

  @override
  Future<void> crateApiInspectorInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInspectorInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<ModelSession> crateApiInspectorOpenModel({
    String? datPath,
    String? dttPath,
    required String candidateId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(datPath, serializer);
          sse_encode_opt_String(dttPath, serializer);
          sse_encode_String(candidateId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_model_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInspectorOpenModelConstMeta,
        argValues: [datPath, dttPath, candidateId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorOpenModelConstMeta => const TaskConstMeta(
    debugName: "open_model",
    argNames: ["datPath", "dttPath", "candidateId"],
  );

  @override
  Future<ArchiveProbe> crateApiInspectorProbeArchivePair({
    String? datPath,
    String? dttPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(datPath, serializer);
          sse_encode_opt_String(dttPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_archive_probe,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInspectorProbeArchivePairConstMeta,
        argValues: [datPath, dttPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorProbeArchivePairConstMeta =>
      const TaskConstMeta(
        debugName: "probe_archive_pair",
        argNames: ["datPath", "dttPath"],
      );

  @override
  Future<TexturePreview> crateApiTextureReadMisctexPreview({
    required String dttPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dttPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_texture_preview,
          decodeErrorData: sse_decode_misc_tex_error,
        ),
        constMeta: kCrateApiTextureReadMisctexPreviewConstMeta,
        argValues: [dttPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTextureReadMisctexPreviewConstMeta =>
      const TaskConstMeta(
        debugName: "read_misctex_preview",
        argNames: ["dttPath"],
      );

  @override
  Future<WeaponRenameResult> crateApiWeaponRenameWeapon({
    required String datPath,
    required String dttPath,
    required String toStem,
    required String outDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(datPath, serializer);
          sse_encode_String(dttPath, serializer);
          sse_encode_String(toStem, serializer);
          sse_encode_String(outDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_weapon_rename_result,
          decodeErrorData: sse_decode_weapon_rename_error,
        ),
        constMeta: kCrateApiWeaponRenameWeaponConstMeta,
        argValues: [datPath, dttPath, toStem, outDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWeaponRenameWeaponConstMeta => const TaskConstMeta(
    debugName: "rename_weapon",
    argNames: ["datPath", "dttPath", "toStem", "outDir"],
  );

  @override
  Future<RenderFrame> crateApiInspectorRenderModel({
    required BigInt sessionId,
    required int width,
    required int height,
    required double yaw,
    required double pitch,
    required double distance,
    required double panX,
    required double panY,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_f_32(yaw, serializer);
          sse_encode_f_32(pitch, serializer);
          sse_encode_f_32(distance, serializer);
          sse_encode_f_32(panX, serializer);
          sse_encode_f_32(panY, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInspectorRenderModelConstMeta,
        argValues: [sessionId, width, height, yaw, pitch, distance, panX, panY],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorRenderModelConstMeta =>
      const TaskConstMeta(
        debugName: "render_model",
        argNames: [
          "sessionId",
          "width",
          "height",
          "yaw",
          "pitch",
          "distance",
          "panX",
          "panY",
        ],
      );

  @override
  Future<void> crateApiInspectorSetMeshVisibility({
    required BigInt sessionId,
    required int meshId,
    required bool visible,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(meshId, serializer);
          sse_encode_bool(visible, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInspectorSetMeshVisibilityConstMeta,
        argValues: [sessionId, meshId, visible],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorSetMeshVisibilityConstMeta =>
      const TaskConstMeta(
        debugName: "set_mesh_visibility",
        argNames: ["sessionId", "meshId", "visible"],
      );

  @override
  Future<void> crateApiInspectorSetModelLod({
    required BigInt sessionId,
    required int lodIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(lodIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInspectorSetModelLodConstMeta,
        argValues: [sessionId, lodIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectorSetModelLodConstMeta =>
      const TaskConstMeta(
        debugName: "set_model_lod",
        argNames: ["sessionId", "lodIndex"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ArchiveProbe dco_decode_archive_probe(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ArchiveProbe(
      candidates: dco_decode_list_model_candidate(arr[0]),
      warnings: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ModelCandidate> dco_decode_list_model_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_candidate).toList();
  }

  @protected
  List<ModelMesh> dco_decode_list_model_mesh(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_mesh).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MiscTexError dco_decode_misc_tex_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MiscTexError(
      code: dco_decode_u_32(arr[0]),
      detail: dco_decode_String(arr[1]),
    );
  }

  @protected
  MiscTexResult dco_decode_misc_tex_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MiscTexResult(
      datPath: dco_decode_String(arr[0]),
      dttPath: dco_decode_String(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
      datBytes: dco_decode_u_64(arr[4]),
      dttBytes: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  ModelCandidate dco_decode_model_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ModelCandidate(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      archive: dco_decode_String(arr[2]),
      entryIndex: dco_decode_u_32(arr[3]),
      hasTextures: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ModelMesh dco_decode_model_mesh(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ModelMesh(
      id: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      lodName: dco_decode_String(arr[2]),
      lodIndex: dco_decode_u_32(arr[3]),
      visible: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ModelSession dco_decode_model_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ModelSession(
      id: dco_decode_u_64(arr[0]),
      vertexCount: dco_decode_u_64(arr[1]),
      triangleCount: dco_decode_u_64(arr[2]),
      lodNames: dco_decode_list_String(arr[3]),
      meshes: dco_decode_list_model_mesh(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RenderFrame dco_decode_render_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RenderFrame(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  TexturePreview dco_decode_texture_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TexturePreview(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      png: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WeaponRenameError dco_decode_weapon_rename_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WeaponRenameError(
      code: dco_decode_u_32(arr[0]),
      detail: dco_decode_String(arr[1]),
    );
  }

  @protected
  WeaponRenameResult dco_decode_weapon_rename_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WeaponRenameResult(
      datPath: dco_decode_String(arr[0]),
      dttPath: dco_decode_String(arr[1]),
      fromStem: dco_decode_String(arr[2]),
      toStem: dco_decode_String(arr[3]),
      renamedEntries: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ArchiveProbe sse_decode_archive_probe(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_candidates = sse_decode_list_model_candidate(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return ArchiveProbe(candidates: var_candidates, warnings: var_warnings);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelCandidate> sse_decode_list_model_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelMesh> sse_decode_list_model_mesh(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelMesh>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_mesh(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MiscTexError sse_decode_misc_tex_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_u_32(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return MiscTexError(code: var_code, detail: var_detail);
  }

  @protected
  MiscTexResult sse_decode_misc_tex_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_datPath = sse_decode_String(deserializer);
    var var_dttPath = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_datBytes = sse_decode_u_64(deserializer);
    var var_dttBytes = sse_decode_u_64(deserializer);
    return MiscTexResult(
      datPath: var_datPath,
      dttPath: var_dttPath,
      width: var_width,
      height: var_height,
      datBytes: var_datBytes,
      dttBytes: var_dttBytes,
    );
  }

  @protected
  ModelCandidate sse_decode_model_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_archive = sse_decode_String(deserializer);
    var var_entryIndex = sse_decode_u_32(deserializer);
    var var_hasTextures = sse_decode_bool(deserializer);
    return ModelCandidate(
      id: var_id,
      name: var_name,
      archive: var_archive,
      entryIndex: var_entryIndex,
      hasTextures: var_hasTextures,
    );
  }

  @protected
  ModelMesh sse_decode_model_mesh(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_lodName = sse_decode_String(deserializer);
    var var_lodIndex = sse_decode_u_32(deserializer);
    var var_visible = sse_decode_bool(deserializer);
    return ModelMesh(
      id: var_id,
      name: var_name,
      lodName: var_lodName,
      lodIndex: var_lodIndex,
      visible: var_visible,
    );
  }

  @protected
  ModelSession sse_decode_model_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_vertexCount = sse_decode_u_64(deserializer);
    var var_triangleCount = sse_decode_u_64(deserializer);
    var var_lodNames = sse_decode_list_String(deserializer);
    var var_meshes = sse_decode_list_model_mesh(deserializer);
    return ModelSession(
      id: var_id,
      vertexCount: var_vertexCount,
      triangleCount: var_triangleCount,
      lodNames: var_lodNames,
      meshes: var_meshes,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RenderFrame sse_decode_render_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return RenderFrame(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  TexturePreview sse_decode_texture_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_png = sse_decode_list_prim_u_8_strict(deserializer);
    return TexturePreview(width: var_width, height: var_height, png: var_png);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WeaponRenameError sse_decode_weapon_rename_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_u_32(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return WeaponRenameError(code: var_code, detail: var_detail);
  }

  @protected
  WeaponRenameResult sse_decode_weapon_rename_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_datPath = sse_decode_String(deserializer);
    var var_dttPath = sse_decode_String(deserializer);
    var var_fromStem = sse_decode_String(deserializer);
    var var_toStem = sse_decode_String(deserializer);
    var var_renamedEntries = sse_decode_list_String(deserializer);
    return WeaponRenameResult(
      datPath: var_datPath,
      dttPath: var_dttPath,
      fromStem: var_fromStem,
      toStem: var_toStem,
      renamedEntries: var_renamedEntries,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_archive_probe(ArchiveProbe self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_model_candidate(self.candidates, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_candidate(
    List<ModelCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_mesh(
    List<ModelMesh> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_mesh(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_misc_tex_error(MiscTexError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.code, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_misc_tex_result(
    MiscTexResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.datPath, serializer);
    sse_encode_String(self.dttPath, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.datBytes, serializer);
    sse_encode_u_64(self.dttBytes, serializer);
  }

  @protected
  void sse_encode_model_candidate(
    ModelCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.archive, serializer);
    sse_encode_u_32(self.entryIndex, serializer);
    sse_encode_bool(self.hasTextures, serializer);
  }

  @protected
  void sse_encode_model_mesh(ModelMesh self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.lodName, serializer);
    sse_encode_u_32(self.lodIndex, serializer);
    sse_encode_bool(self.visible, serializer);
  }

  @protected
  void sse_encode_model_session(ModelSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_u_64(self.vertexCount, serializer);
    sse_encode_u_64(self.triangleCount, serializer);
    sse_encode_list_String(self.lodNames, serializer);
    sse_encode_list_model_mesh(self.meshes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_render_frame(RenderFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_texture_preview(
    TexturePreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.png, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_weapon_rename_error(
    WeaponRenameError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.code, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_weapon_rename_result(
    WeaponRenameResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.datPath, serializer);
    sse_encode_String(self.dttPath, serializer);
    sse_encode_String(self.fromStem, serializer);
    sse_encode_String(self.toStem, serializer);
    sse_encode_list_String(self.renamedEntries, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
