// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/inspector.dart';
import 'api/texture.dart';
import 'api/weapon.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ArchiveProbe dco_decode_archive_probe(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ModelCandidate> dco_decode_list_model_candidate(dynamic raw);

  @protected
  List<ModelMesh> dco_decode_list_model_mesh(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MiscTexError dco_decode_misc_tex_error(dynamic raw);

  @protected
  MiscTexResult dco_decode_misc_tex_result(dynamic raw);

  @protected
  ModelCandidate dco_decode_model_candidate(dynamic raw);

  @protected
  ModelMesh dco_decode_model_mesh(dynamic raw);

  @protected
  ModelSession dco_decode_model_session(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RenderFrame dco_decode_render_frame(dynamic raw);

  @protected
  TexturePreview dco_decode_texture_preview(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WeaponRenameError dco_decode_weapon_rename_error(dynamic raw);

  @protected
  WeaponRenameResult dco_decode_weapon_rename_result(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArchiveProbe sse_decode_archive_probe(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ModelCandidate> sse_decode_list_model_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelMesh> sse_decode_list_model_mesh(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MiscTexError sse_decode_misc_tex_error(SseDeserializer deserializer);

  @protected
  MiscTexResult sse_decode_misc_tex_result(SseDeserializer deserializer);

  @protected
  ModelCandidate sse_decode_model_candidate(SseDeserializer deserializer);

  @protected
  ModelMesh sse_decode_model_mesh(SseDeserializer deserializer);

  @protected
  ModelSession sse_decode_model_session(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RenderFrame sse_decode_render_frame(SseDeserializer deserializer);

  @protected
  TexturePreview sse_decode_texture_preview(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WeaponRenameError sse_decode_weapon_rename_error(
    SseDeserializer deserializer,
  );

  @protected
  WeaponRenameResult sse_decode_weapon_rename_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_archive_probe(ArchiveProbe self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_model_candidate(
    List<ModelCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_mesh(
    List<ModelMesh> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_misc_tex_error(MiscTexError self, SseSerializer serializer);

  @protected
  void sse_encode_misc_tex_result(MiscTexResult self, SseSerializer serializer);

  @protected
  void sse_encode_model_candidate(
    ModelCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_mesh(ModelMesh self, SseSerializer serializer);

  @protected
  void sse_encode_model_session(ModelSession self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_render_frame(RenderFrame self, SseSerializer serializer);

  @protected
  void sse_encode_texture_preview(
    TexturePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_weapon_rename_error(
    WeaponRenameError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weapon_rename_result(
    WeaponRenameResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
