// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `entry_stem`, `has_texture_pair`, `load_texture_files`, `read_named`, `sessions`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ArchiveProbe> probeArchivePair({String? datPath, String? dttPath}) =>
    RustLib.instance.api.crateApiInspectorProbeArchivePair(
      datPath: datPath,
      dttPath: dttPath,
    );

Future<ModelSession> openModel({
  String? datPath,
  String? dttPath,
  required String candidateId,
}) => RustLib.instance.api.crateApiInspectorOpenModel(
  datPath: datPath,
  dttPath: dttPath,
  candidateId: candidateId,
);

Future<RenderFrame> renderModel({
  required BigInt sessionId,
  required int width,
  required int height,
  required double yaw,
  required double pitch,
  required double distance,
  required double panX,
  required double panY,
}) => RustLib.instance.api.crateApiInspectorRenderModel(
  sessionId: sessionId,
  width: width,
  height: height,
  yaw: yaw,
  pitch: pitch,
  distance: distance,
  panX: panX,
  panY: panY,
);

Future<void> setMeshVisibility({
  required BigInt sessionId,
  required int meshId,
  required bool visible,
}) => RustLib.instance.api.crateApiInspectorSetMeshVisibility(
  sessionId: sessionId,
  meshId: meshId,
  visible: visible,
);

Future<void> setModelLod({required BigInt sessionId, required int lodIndex}) =>
    RustLib.instance.api.crateApiInspectorSetModelLod(
      sessionId: sessionId,
      lodIndex: lodIndex,
    );

void closeModel({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiInspectorCloseModel(sessionId: sessionId);

class ArchiveProbe {
  final List<ModelCandidate> candidates;
  final List<String> warnings;

  const ArchiveProbe({required this.candidates, required this.warnings});

  @override
  int get hashCode => candidates.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveProbe &&
          runtimeType == other.runtimeType &&
          candidates == other.candidates &&
          warnings == other.warnings;
}

class ModelCandidate {
  final String id;
  final String name;
  final String archive;
  final int entryIndex;
  final bool hasTextures;

  const ModelCandidate({
    required this.id,
    required this.name,
    required this.archive,
    required this.entryIndex,
    required this.hasTextures,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      archive.hashCode ^
      entryIndex.hashCode ^
      hasTextures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelCandidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          archive == other.archive &&
          entryIndex == other.entryIndex &&
          hasTextures == other.hasTextures;
}

class ModelMesh {
  final int id;
  final String name;
  final String lodName;
  final int lodIndex;
  final bool visible;

  const ModelMesh({
    required this.id,
    required this.name,
    required this.lodName,
    required this.lodIndex,
    required this.visible,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      lodName.hashCode ^
      lodIndex.hashCode ^
      visible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelMesh &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lodName == other.lodName &&
          lodIndex == other.lodIndex &&
          visible == other.visible;
}

class ModelSession {
  final BigInt id;
  final BigInt vertexCount;
  final BigInt triangleCount;
  final List<String> lodNames;
  final List<ModelMesh> meshes;

  const ModelSession({
    required this.id,
    required this.vertexCount,
    required this.triangleCount,
    required this.lodNames,
    required this.meshes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      vertexCount.hashCode ^
      triangleCount.hashCode ^
      lodNames.hashCode ^
      meshes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vertexCount == other.vertexCount &&
          triangleCount == other.triangleCount &&
          lodNames == other.lodNames &&
          meshes == other.meshes;
}

class RenderFrame {
  final int width;
  final int height;
  final Uint8List rgba;

  const RenderFrame({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
