// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

Future<TexturePreview> readMisctexPreview({required String dttPath}) =>
    RustLib.instance.api.crateApiTextureReadMisctexPreview(dttPath: dttPath);

Future<MiscTexResult> createItemThumbnail({
  required String sourceImagePath,
  required String outputDir,
  required String textureName,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiTextureCreateItemThumbnail(
  sourceImagePath: sourceImagePath,
  outputDir: outputDir,
  textureName: textureName,
  width: width,
  height: height,
);

class MiscTexError implements FrbException {
  final int code;
  final String detail;

  const MiscTexError({required this.code, required this.detail});

  @override
  int get hashCode => code.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MiscTexError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          detail == other.detail;
}

class MiscTexResult {
  final String datPath;
  final String dttPath;
  final int width;
  final int height;
  final BigInt datBytes;
  final BigInt dttBytes;

  const MiscTexResult({
    required this.datPath,
    required this.dttPath,
    required this.width,
    required this.height,
    required this.datBytes,
    required this.dttBytes,
  });

  @override
  int get hashCode =>
      datPath.hashCode ^
      dttPath.hashCode ^
      width.hashCode ^
      height.hashCode ^
      datBytes.hashCode ^
      dttBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MiscTexResult &&
          runtimeType == other.runtimeType &&
          datPath == other.datPath &&
          dttPath == other.dttPath &&
          width == other.width &&
          height == other.height &&
          datBytes == other.datBytes &&
          dttBytes == other.dttBytes;
}

class TexturePreview {
  final int width;
  final int height;
  final Uint8List png;

  const TexturePreview({
    required this.width,
    required this.height,
    required this.png,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ png.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TexturePreview &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          png == other.png;
}
