// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`

Future<WeaponRenameResult> renameWeapon({
  required String datPath,
  required String dttPath,
  required String toStem,
  required String outDir,
}) => RustLib.instance.api.crateApiWeaponRenameWeapon(
  datPath: datPath,
  dttPath: dttPath,
  toStem: toStem,
  outDir: outDir,
);

class WeaponRenameError implements FrbException {
  final int code;
  final String detail;

  const WeaponRenameError({required this.code, required this.detail});

  @override
  int get hashCode => code.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeaponRenameError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          detail == other.detail;
}

class WeaponRenameResult {
  final String datPath;
  final String dttPath;
  final String fromStem;
  final String toStem;
  final List<String> renamedEntries;

  const WeaponRenameResult({
    required this.datPath,
    required this.dttPath,
    required this.fromStem,
    required this.toStem,
    required this.renamedEntries,
  });

  @override
  int get hashCode =>
      datPath.hashCode ^
      dttPath.hashCode ^
      fromStem.hashCode ^
      toStem.hashCode ^
      renamedEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeaponRenameResult &&
          runtimeType == other.runtimeType &&
          datPath == other.datPath &&
          dttPath == other.dttPath &&
          fromStem == other.fromStem &&
          toStem == other.toStem &&
          renamedEntries == other.renamedEntries;
}
